### ISSUE TITLE
bhealth.metric_wrappers.Wrapper with the argument csv_prep generates exception

### ISSUE THREAD

**Issue by perellonieto** [rymc/bHealth#13]
On every example in the examples folder, if the csv_prep argument when creating a Wrapper is set, the plot_metrics will raise the following exception

```
Traceback (most recent call last):
  File "synthetic_long_example.py", line 210, in <module>
    figures_dict = plot_metrics(metric_container_daily, date_container_daily, labels_=labels)
  File "../bhealth/visualisations.py", line 96, in plot_metrics
    for key in proportion:
TypeError: 'float' object is not iterable
```

To avoid the exception I have removed the optional argument from all the examples, but needs to be investigated.

**Comment by mkoz71** [comment]
This seems to change whenever you use run_metric_array, as opposed to run_metric_array_csv. I suspect the csv parameter sets one of the metrics as a float, when the function expects integers.
